FROM node:20-alpine3.17

LABEL version="1.0"
LABEL description="This is the base docker image for the synonyms search test backend API."
LABEL maintainer = ["tao_sun@hotmail.com"]

WORKDIR /app

COPY ["package*.json", "./"]

RUN npm install 
COPY . .

CMD [ "npm", "run", "test" ]
